baseURL: 'https://alberto-eusebio.netlify.app'
languageCode: en-us
title: Alberto Eusebio
theme: ["PaperMod"]
mode: profileMode

Menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  profileMode:
    enabled: true
    title: "<Title>" # optional default will be site title
    subtitle: "
      Hello newcomers 👋 I am Alberto, a [**Ms.c student in Computer Science and Engineering**](https://www4.ceda.polimi.it/manifesti/manifesti/controller/ManifestoPublic.do?check_params=1&aa=2023&k_corso_la=481&k_indir=T2I&polij_device_category=DESKTOP&__pj0=0&__pj1=3aae52e91c120d3e5c102e7bf88678eb) at Politecnico di Milano specializing in **Artificial Intelligence** 🦾<br>
      In my Bs.c I studied [**Computer Engineering**](https://www.polito.it/en/education/bachelor-s-degree-programmes/computer-engineering) at Politecnico di Torino, where I graduated Cum Laude in 2022.<br>
      In my bachelor I have joined [**Team Policumbent**](https://www.policumbent.it/en/) in the development of the World fastest human powered vehicles, competing in the **World Human powered Speed Challenge**, which we won under my leadership in 2022 🚀<br>
      I have been involved in the [**Intraprendenti Project**](https://www.polito.it/didattica/teaching-lab-progetti-didattici/honors-programs/percorso-intraprendenti) and I am now part of the [**ASP PROJECT**](https://www.asp-poli.it/) , both merit-based multidisciplinary programs aimed at 150 exceptionally talented and motivated students in Engineering, Design and Architecture 🏅"
    imageUrl: "home/me_big.jpg" # optional
    imageTitle: "Here I am!" # optional
    imageWidth: 220 # optional
    imageHeight: 220 # optional

  socialIcons: # optional
    - name: "email"
      url: "mailto:albertoeusebio72@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/alberto-eusebio/"
    - name: "github"
      url: "https://github.com/AlbertoEusebio"
    - name: "cv"
      url: "https://drive.google.com/file/d/1DpWDI0-52nw3AZxO_55cGsD-QI1xpxVK/view"